name: Format

on: push

jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: python3 src/convert.py
      - uses: stefanzweifel/git-auto-commit-action@v5
